
CHROME = 'chrome'
FIREFOX = 'firefox'
INTERNET_EXPLORER = 'ie'
SAFARI = 'safari'
OPERA = 'opera'
EDGE = 'edge'

SAFARI_IPHONE = 'safari_iphone'
SAFARI_IPAD = 'safari_ipad'

GALAXYS5 = 'galaxys5'
NEXUS5X = 'nexus5x'
NEXUS6P = 'nexus6p'
IPHONE5 = 'iphone5'
IPHONE6 = 'iphone6'
IPHONE6PLUS = 'iphone6plus'
IPAD = 'ipad'
IPADPRO = 'ipadpro'

ANDROID = 'android'
IPHONE = 'iphone'

PHANTOMJS = 'phantomjs'

DESKTOP_BROWSERS = [CHROME, FIREFOX, EDGE, INTERNET_EXPLORER, SAFARI]
DEVICE_EMULATION_BROWSERS = [NEXUS5X, NEXUS6P, GALAXYS5, IPAD, IPADPRO, IPHONE5, IPHONE6, IPHONE6PLUS, SAFARI_IPHONE, SAFARI_IPAD]
MOBILE_EMULATION_BROWERS = [NEXUS5X, NEXUS6P, GALAXYS5, IPHONE5, IPHONE6, IPHONE6PLUS, SAFARI_IPHONE]
TABLET_EMULATION_BROWERS = [IPAD, IPADPRO, SAFARI_IPAD]
MOBILE_DEVICES = [ANDROID, IPHONE]
